import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { hrefForSlug, urlDirForSlug } from "../url-taxonomy.mjs";
import { escapeHtml } from "../lib/text.mjs";
import { sectionHeading } from "../render/components.mjs";
import { layout } from "../render/layout.mjs";
import { tr } from "../i18n/index.mjs";
import { absoluteUrl } from "../render/urls.mjs";

const _dir = path.dirname(fileURLToPath(import.meta.url));
const transcriptDir = path.join(_dir, "..", "content", "video-transcripts");

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

function formatDate(iso) {
  const s = String(iso || "");
  if (s.length < 10) return s || "Undated";
  const month = MONTHS[Number(s.slice(5, 7)) - 1] || "";
  const day = String(Number(s.slice(8, 10)) || "");
  const year = s.slice(0, 4);
  return `${month} ${day}, ${year}`;
}

/** Load all video transcript records keyed by video id. */
export function loadVideoRecords() {
  const records = [];
  if (!fs.existsSync(transcriptDir)) return records;
  for (const entry of fs.readdirSync(transcriptDir)) {
    if (!entry.endsWith(".json")) continue;
    const full = path.join(transcriptDir, entry);
    try {
      const data = JSON.parse(fs.readFileSync(full, "utf8"));
      if (data.id) records.push(data);
    } catch {
      // skip malformed files
    }
  }
  return records;
}

/** Map from video page slug (video-<id>) to record. */
let _recordsBySlug = null;
export function videoRecordBySlug(slug) {
  if (_recordsBySlug === null) {
    _recordsBySlug = new Map(
      loadVideoRecords().map((r) => [`video-${r.id}`, r]),
    );
  }
  return _recordsBySlug.get(slug) || null;
}

/** All video page slugs registered for sitemap/build. */
export function allVideoSlugs() {
  return loadVideoRecords().map((r) => `video-${r.id}`);
}

/**
 * Render a single video detail page.
 * @param {object} record - The video transcript record
 * @returns {string} HTML
 */
export function videoDetailPage(record) {
  const slug = `video-${record.id}`;
  const currentDir = urlDirForSlug(slug);
  const seriesLabel = [record.series, record.number].filter(Boolean).join(" ");
  const dateStr = formatDate(record.date);

  const guestNames = (record.guests || []).filter(Boolean);
  const guestList = guestNames.length
    ? guestNames.map((n) => escapeHtml(n)).join(", ")
    : "";

  // YouTube link
  const youtubeLink = record.youtubeUrl
    ? `<a class="button primary" href="${escapeHtml(record.youtubeUrl)}" target="_blank" rel="noopener noreferrer">▶ Watch on YouTube ↗</a>`
    : "";

  // Transcript section
  let transcriptSection = "";
  if (record.hasTranscript && record.transcriptExcerpt) {
    transcriptSection = `
  <section class="content-band" id="transcript">
    ${sectionHeading({
      eyebrow: "Transcript",
      title: "AI-generated transcript excerpt",
      text: "The full transcript is available on GitHub. This excerpt is generated by automated speech recognition and may contain errors.",
    })}
    <div class="transcript-block">
      <p>${escapeHtml(record.transcriptExcerpt)}</p>
    </div>
    ${
      record.transcriptSource
        ? `<p class="section-link"><a href="${escapeHtml(record.transcriptSource)}" target="_blank" rel="noopener noreferrer">View full transcript on GitHub ↗</a></p>`
        : ""
    }
  </section>`;
  } else if (record.hasTranscript) {
    transcriptSection = `
  <section class="content-band" id="transcript">
    ${sectionHeading({
      eyebrow: "Transcript",
      title: "Transcript available",
      text: "A transcript is available for this session.",
    })}
    ${
      record.transcriptSource
        ? `<p class="section-link"><a href="${escapeHtml(record.transcriptSource)}" target="_blank" rel="noopener noreferrer">View transcript on GitHub ↗</a></p>`
        : ""
    }
  </section>`;
  }

  // Keywords/topics
  const keywords = (record.keywords || []).filter(Boolean);
  const ontologyTerms = (record.ontologyTerms || []).filter(Boolean);
  const topicTags = [...keywords, ...ontologyTerms.map((t) => t.replace(/^term-/, "").replace(/-/g, " "))];
  const topicSection =
    topicTags.length > 0
      ? `<div class="tag-row">${topicTags.map((t) => `<span>${escapeHtml(t)}</span>`).join("")}</div>`
      : "";

  const body = `
  <section class="page-hero compact">
    <nav class="breadcrumb" aria-label="Breadcrumb">
      <a href="${hrefForSlug("index", currentDir)}">Home</a>
      <span aria-hidden="true">/</span>
      <a href="${hrefForSlug("video", currentDir)}">Videos and Podcasts</a>
      <span aria-hidden="true">/</span>
      <span aria-current="page">${escapeHtml(record.title || "Untitled")}</span>
    </nav>
    <p class="eyebrow">${escapeHtml(seriesLabel || "Video session")}</p>
    <h1>${escapeHtml(record.title || "Untitled")}</h1>
    <p>${escapeHtml(dateStr)}${guestList ? ` · with ${guestList}` : ""}</p>
    ${youtubeLink}
  </section>

  <section class="content-band muted">
    <div class="resource-grid compact-grid">
      <article class="info-card">
        <h3>Session details</h3>
        <p><strong>Date:</strong> ${escapeHtml(dateStr)}</p>
        ${seriesLabel ? `<p><strong>Series:</strong> ${escapeHtml(seriesLabel)}</p>` : ""}
        ${guestList ? `<p><strong>Guests:</strong> ${escapeHtml(guestList)}</p>` : ""}
        ${record.paperTitle ? `<p><strong>Paper:</strong> ${escapeHtml(record.paperTitle)}</p>` : ""}
      </article>
      <article class="info-card">
        <h3>Watch and follow up</h3>
        ${record.youtubeUrl ? `<p><a href="${escapeHtml(record.youtubeUrl)}" target="_blank" rel="noopener noreferrer">▶ Watch on YouTube ↗</a></p>` : ""}
        ${record.githubUrl ? `<p><a href="${escapeHtml(record.githubUrl)}" target="_blank" rel="noopener noreferrer">View on GitHub ↗</a></p>` : ""}
        <p><a href="${hrefForSlug("video", currentDir)}">← Back to video library</a></p>
      </article>
    </div>
    ${topicSection}
  </section>

  ${transcriptSection}

  <section class="content-band" id="related">
    ${sectionHeading({
      eyebrow: "Continue",
      title: "More from the video library",
      text: "Browse the complete library or find more sessions in this series.",
    })}
    <div class="link-chips">
      <a href="${hrefForSlug("video", currentDir)}"><span>All videos</span></a>
      <a href="${hrefForSlug("activities", currentDir)}"><span>Activities</span></a>
      <a href="${hrefForSlug("learning", currentDir)}"><span>Learning</span></a>
    </div>
  </section>`;

  return layout({
    title: record.title || "Video session",
    description: `Recorded session${seriesLabel ? ` from ${seriesLabel}` : ""}${guestList ? ` with ${guestList}` : ""}.`,
    currentDir,
    body,
    slug,
  });
}
