import {
  copyFileSync,
  existsSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
// The design-system SOURCE lives in the sibling monorepo (../../library/design-system).
// Override with INSTITUTEOS_DS_ROOT. When the source is present we re-export it and
// byte-compare to catch a stale committed CSS; when it is absent (a standalone checkout,
// e.g. this repo's own CI) we skip that freshness comparison and validate only what is
// self-contained here — that styles.css's token fallbacks match the committed
// instituteos-ds.css.
const designSystemRoot = process.env.INSTITUTEOS_DS_ROOT
  ? resolve(process.env.INSTITUTEOS_DS_ROOT)
  : resolve(root, "../../library/design-system");
const websiteCss = resolve(root, "assets/css/instituteos-ds.css");
const websiteFonts = resolve(root, "assets/css/fonts");

const read = (filePath) => readFileSync(filePath, "utf8");
const readBuffer = (filePath) => readFileSync(filePath);
const sameFile = (left, right) => Buffer.compare(readBuffer(left), readBuffer(right)) === 0;
const fontFiles = (dir) => readdirSync(dir).filter((name) => name.endsWith(".woff2")).sort();

const errors = [];

// Canonical token values come from the fresh export when the DS source is available,
// otherwise from the committed instituteos-ds.css (which IS that export). Both yield
// the same dark-theme :root values, so the fallback check is identical either way.
let canonicalSourceCss = websiteCss;
let freshnessChecked = false;

if (existsSync(designSystemRoot)) {
  const header = `/* InstituteOS Design System — standalone brand fonts + tokens + primitives.
 * Generated by scripts/export-css.mjs from @instituteos/design-system.
 * Framework-free: <link> this into any page (dashboard, website) to get the
 * full brand surface, including self-hosted Fraunces / Inter Tight / JetBrains
 * Mono (./fonts/). "Act. Infer. Serve." */\n\n`;
  const designSystemPath = (relativePath) => resolve(designSystemRoot, relativePath);
  const combined =
    header +
    read(designSystemPath("src/styles/brand-fonts.css")) +
    "\n" +
    read(designSystemPath("src/styles/tokens.css")) +
    "\n" +
    read(designSystemPath("src/styles/primitives.css")) +
    "\n" +
    read(designSystemPath("src/styles/components.css"));

  const tempDir = mkdtempSync(resolve(tmpdir(), "instituteos-ds-"));
  const tempCss = resolve(tempDir, "instituteos-ds.css");
  const tempFonts = resolve(tempDir, "fonts");
  mkdirSync(tempFonts, { recursive: true });
  writeFileSync(tempCss, combined);

  for (const name of readdirSync(designSystemPath("src/styles/fonts"))) {
    if (name.endsWith(".woff2")) {
      copyFileSync(designSystemPath(`src/styles/fonts/${name}`), resolve(tempFonts, name));
    }
  }

  if (!sameFile(tempCss, websiteCss)) {
    errors.push(`Website design-system CSS is stale: ${websiteCss}`);
  }

  const expectedFonts = fontFiles(tempFonts);
  const actualFonts = fontFiles(websiteFonts);
  if (expectedFonts.join("\n") !== actualFonts.join("\n")) {
    errors.push(`Website design-system font list differs from export: ${websiteFonts}`);
  } else {
    for (const name of expectedFonts) {
      const expected = resolve(tempFonts, name);
      const actual = resolve(websiteFonts, name);
      if (statSync(expected).size !== statSync(actual).size || !sameFile(expected, actual)) {
        errors.push(`Website design-system font is stale: ${actual}`);
      }
    }
  }

  canonicalSourceCss = tempCss;
  freshnessChecked = true;
} else {
  console.log(
    `NOTE: design-system source not found at ${designSystemRoot}; skipping export ` +
      `freshness check (standalone checkout). Validating styles.css fallbacks against ` +
      `the committed ${websiteCss}.`,
  );
}

// Enforce that the website's styles.css fallbacks stay aligned with the canonical
// tokens. styles.css references design-system variables as `var(--ds-x, <fallback>)`;
// those fallbacks render only if instituteos-ds.css fails to load, so they must equal
// the canonical (dark) token value to keep the brand intact in that degraded state.
// Canonical values are read from canonicalSourceCss — never a hardcoded list — so this
// check can never drift from the source of truth.
const websiteStyles = resolve(root, "assets/css/styles.css");

const stripComments = (css) => css.replace(/\/\*[\s\S]*?\*\//g, "");

function parseRootVars(rawCss) {
  // Strip comments first: a comment containing a colon (e.g. "/* Brand: red */")
  // would otherwise be mis-parsed as a declaration and swallow the token after it.
  const css = stripComments(rawCss);
  // The first :root { ... } block holds the dark-mode defaults.
  const match = css.match(/:root\s*\{([^}]*)\}/);
  const map = new Map();
  if (match) {
    for (const decl of match[1].split(";")) {
      const colon = decl.indexOf(":");
      if (colon === -1) continue;
      const name = decl.slice(0, colon).trim();
      if (name.startsWith("--ds-")) map.set(name, decl.slice(colon + 1).trim());
    }
  }
  return map;
}

function findDsVarRefs(rawCss) {
  // Returns {name, fallback} for every var(--ds-x, <fallback>), tolerating nested
  // parens in the fallback (e.g. rgba(), color-mix()). Comments stripped so a
  // commented-out reference is never flagged.
  const css = stripComments(rawCss);
  const refs = [];
  let i = 0;
  while ((i = css.indexOf("var(", i)) !== -1) {
    let depth = 1;
    let k = i + 4;
    for (; k < css.length && depth > 0; k++) {
      if (css[k] === "(") depth++;
      else if (css[k] === ")") depth--;
      if (depth === 0) break;
    }
    const inner = css.slice(i + 4, k);
    const comma = inner.indexOf(",");
    if (comma !== -1) {
      const name = inner.slice(0, comma).trim();
      if (name.startsWith("--ds-")) refs.push({ name, fallback: inner.slice(comma + 1).trim() });
    }
    i = k + 1;
  }
  return refs;
}

const normalizeValue = (value) => value.replace(/\s+/g, "").replace(/["']/g, "").toLowerCase();
// Font/motion tokens are formatting-sensitive (stack ordering, units) and are
// validated by the byte-compare of instituteos-ds.css itself, not here.
const fallbackSkip = new Set(["--ds-font-body", "--ds-font-display", "--ds-font-mono", "--ds-motion", "--ds-ease"]);

const canonicalTokens = parseRootVars(read(canonicalSourceCss).toString());
const styleCss = read(websiteStyles).toString();
const reportedFallbacks = new Set();
for (const { name, fallback } of findDsVarRefs(styleCss)) {
  if (fallbackSkip.has(name) || !canonicalTokens.has(name)) continue;
  const canonical = canonicalTokens.get(name);
  if (normalizeValue(fallback) !== normalizeValue(canonical) && !reportedFallbacks.has(name + fallback)) {
    reportedFallbacks.add(name + fallback);
    errors.push(`styles.css fallback for ${name} is "${fallback}" but the design-system value is "${canonical}"`);
  }
}

if (errors.length) {
  console.error(errors.map((error) => `- ${error}`).join("\n"));
  console.error("Run: npm run export:website -- --to ../../repos/institute_website/assets/css/instituteos-ds.css");
  console.error("Fallback mismatches: update assets/css/styles.css :root to match the canonical token values.");
  process.exit(1);
}

if (freshnessChecked) {
  console.log(`PASS: website design-system export matches ${websiteCss}`);
}
console.log(`PASS: styles.css design-system fallbacks match canonical tokens`);
